From mhart/alpine-node:10 AS base
  
WORKDIR /app

FROM base AS development
COPY package.json yarn.lock lerna.json /app/

COPY apps/covid-api /app/apps/covid-api/

# Use app directory as current workdir
ENV PATH /app/node_modules/.bin:$PATH

RUN yarn install --pure-lockfile --production
RUN cp -R node_modules /tmp/node_modules

RUN yarn install --pure-lockfile
COPY . .

FROM development AS builder
RUN mkdir -p apps/covid-api/public/
RUN touch apps/covid-api/public/covid19_US_CA_County.json
RUN yarn workspace covid-api build
RUN cp -R apps/covid-api /tmp/covid-api

FROM base AS release
COPY --from=builder /tmp/node_modules ./node_modules
COPY --from=builder /tmp/covid-api /app/apps/covid-api
COPY --from=builder /app/package.json /app/

RUN apk update
RUN apk add lftp